stages:
   - deploy

before_script:
   - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
   - eval $(ssh-agent -s)
   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh

deploy-prod-job:
   stage: deploy
   only:
       - master
   script:
       - echo "${DEPLOY_PRIVATE_SSH_KEY_PROD:-$DEPLOY_PRIVATE_SSH_KEY_DEV}" | tr -d '\r' | ssh-add -
       - echo "Deploying the PROD project..."
       - ssh -tt -o StrictHostKeyChecking=no -p ${DEPLOY_PORT_PROD:-${DEPLOY_PORT_DEV:-22}} ${DEPLOY_HOST_PROD:-$DEPLOY_HOST_DEV} \
           "cd ${DEPLOY_PATH_PROD:-/root/sites/${CI_PROJECT_NAME}/} &&
           git reset --hard &&
           git pull origin master &&
           docker compose down &&
           docker compose up -d --build &&
           docker compose exec php composer install"
